# Generated by Django 5.0.3 on 2024-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0002_remove_joboffer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="interview_rh",
            field=models.CharField(
                choices=[("green", "Vert"), ("red", "Rouge"), ("gray", "Gris")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="interview_technical",
            field=models.CharField(
                choices=[("green", "Vert"), ("red", "Rouge"), ("gray", "Gris")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="status",
            field=models.CharField(
                choices=[("green", "Vert"), ("red", "Rouge"), ("gray", "Gris")],
                default="",
                max_length=10,
            ),
        ),
    ]
