# Generated by Django 5.0.3 on 2024-03-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0004_alter_joboffer_interview_rh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="interview_rh",
            field=models.CharField(
                blank=True,
                choices=[("green", "Vert"), ("red", "Rouge"), ("gray", "Gris")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="interview_technical",
            field=models.CharField(
                blank=True,
                choices=[("green", "Vert"), ("red", "Rouge"), ("gray", "Gris")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("green", "Vert"), ("red", "Rouge"), ("gray", "Gris")],
                max_length=10,
            ),
        ),
    ]
