# Generated by Django 5.0.3 on 2024-03-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0006_alter_joboffer_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
