# Generated by Django 5.0.3 on 2024-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0007_alter_joboffer_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joboffer",
            name="comment",
        ),
        migrations.AddField(
            model_name="joboffer",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
