# Generated by Django 5.0.3 on 2024-03-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0008_remove_joboffer_comment_joboffer_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="number",
            field=models.IntegerField(),
        ),
    ]
