# Generated by Django 5.0.3 on 2024-03-11 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0010_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joboffer",
            name="interview_rh",
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="interview_technical",
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="status",
        ),
    ]
