# Generated by Django 5.0.3 on 2024-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0012_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="number",
            field=models.IntegerField(default=1),
        ),
    ]
