# Generated by Django 5.0.3 on 2024-03-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0013_alter_joboffer_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="url",
            field=models.URLField(default="https://www.welcometothejungle.com/fr"),
        ),
    ]
